import type { Category, Question } from "../shared/types";

type QuestionEntry = [string, string, string, string, string];

function makeQuestions(entries: QuestionEntry[]): Question[] {
  return entries.map(([question, correctAnswer, wrongA, wrongB, wrongC]) => ({
    question,
    choices: [correctAnswer, wrongA, wrongB, wrongC],
    correctAnswer
  }));
}

export const fallbackQuestions: Record<Category, Question[]> = {
  Animals: makeQuestions([
    ["What is the largest land animal?", "Elephant", "Rhino", "Hippo", "Giraffe"],
    ["Which animal is known for changing color?", "Chameleon", "Panda", "Penguin", "Koala"],
    ["What do caterpillars become?", "Butterflies", "Frogs", "Crabs", "Sparrows"],
    ["Which bird cannot fly?", "Ostrich", "Eagle", "Robin", "Parrot"],
    ["What animal is famous for building dams?", "Beaver", "Fox", "Seal", "Moose"],
    ["How many legs does a spider have?", "8", "6", "10", "12"],
    ["What is a baby goat called?", "Kid", "Cub", "Calf", "Joey"],
    ["Which animal is the tallest?", "Giraffe", "Camel", "Horse", "Bison"],
    ["What do pandas mostly eat?", "Bamboo", "Fish", "Apples", "Grass"],
    ["Which sea animal has eight arms?", "Octopus", "Dolphin", "Sea turtle", "Clam"],
    ["Which mammal can truly fly instead of only glide?", "Bat", "Flying squirrel", "Sugar glider", "Colugo"],
    ["What is the name for animals that are active mostly at night?", "Nocturnal", "Migratory", "Venomous", "Amphibious"],
    ["Which animal group does a salamander belong to?", "Amphibians", "Reptiles", "Fish", "Mammals"],
    ["What do baleen whales use baleen plates for?", "Filtering food from water", "Making loud clicks", "Digging in sand", "Steering while swimming"],
    ["Which big cat is best known for its black tear-like facial marks?", "Cheetah", "Lion", "Jaguar", "Leopard"],
    ["Which animal has the strongest known bite force among living reptiles?", "Saltwater crocodile", "Komodo dragon", "Green iguana", "American alligator"],
    ["What is the only continent where penguins live naturally north of the equator?", "South America", "Africa", "Europe", "Asia"],
    ["Which animal uses echolocation to hunt insects in the dark?", "Bat", "Hedgehog", "Owl", "Raccoon"],
    ["What is a group of lions called?", "Pride", "Herd", "Flock", "School"],
    ["Which bird is known for mimicking human speech?", "Parrot", "Swan", "Pelican", "Falcon"],
    ["What is the fastest land animal?", "Cheetah", "Pronghorn", "Lion", "Horse"],
    ["Which animal lays eggs and is also a mammal?", "Platypus", "Otter", "Meerkat", "Armadillo"],
    ["What do you call an animal that eats both plants and meat?", "Omnivore", "Herbivore", "Carnivore", "Detritivore"],
    ["Which insect communicates by dancing to show food locations?", "Honeybee", "Dragonfly", "Firefly", "Ladybug"],
    ["What is the largest species of shark?", "Whale shark", "Great white shark", "Hammerhead shark", "Tiger shark"],
    ["Which animal has fingerprints very similar to humans?", "Koala", "Kangaroo", "Sloth", "Lemur"],
    ["What is the hard outer skeleton of insects called?", "Exoskeleton", "Endoskeleton", "Shell plate", "Cartilage"],
    ["Which reptile can detach its tail to escape predators?", "Lizard", "Turtle", "Crocodile", "Python"],
    ["What type of animal is a narwhal?", "Whale", "Seal", "Shark", "Dolphin fish"],
    ["Which animal is known for using tools to crack shellfish?", "Sea otter", "Walrus", "Manatee", "Seal"],
    ["What is the largest living bird by wingspan?", "Wandering albatross", "Bald eagle", "Condor", "Pelican"],
    ["Which animal has a tongue that can be longer than its body?", "Chameleon", "Frog", "Gecko", "Iguana"],
    ["What is the name for a frog when it is still young and lives in water?", "Tadpole", "Larva", "Nymph", "Fry"],
    ["Which animal is a marsupial?", "Kangaroo", "Rabbit", "Deer", "Fox"],
    ["What do snakes use to smell the air?", "Tongue", "Ears", "Scales", "Tail"],
    ["Which whale is famous for its long songs?", "Humpback whale", "Beluga whale", "Blue whale", "Gray whale"],
    ["What animal has a prehensile tail often used for gripping branches?", "Monkey", "Wolf", "Antelope", "Hedgehog"],
    ["Which animal is the largest primate?", "Gorilla", "Chimpanzee", "Orangutan", "Mandrill"],
    ["What do emperor penguins do with their eggs during incubation?", "Balance them on their feet", "Bury them in sand", "Hang them from rocks", "Float them in water"],
    ["Which animal has black and white stripes unique to each individual?", "Zebra", "Tiger", "Skunk", "Badger"],
    ["What is the smallest type of bird?", "Hummingbird", "Finch", "Sparrow", "Wren"],
    ["Which sea creature is known for having three hearts?", "Octopus", "Starfish", "Lobster", "Jellyfish"],
    ["What do you call animals without backbones?", "Invertebrates", "Vertebrates", "Mammals", "Amphibians"],
    ["Which mammal is known for rolling into a ball with armor-like scales?", "Pangolin", "Armadillo", "Porcupine", "Hedgehog"],
    ["Which animal is a natural predator of termites and has a long sticky tongue?", "Anteater", "Tapir", "Capybara", "Wombat"],
    ["What is the main purpose of a camel hump?", "Storing fat", "Holding water", "Cooling blood", "Carrying babies"],
    ["Which bird can hover in place while feeding?", "Hummingbird", "Crow", "Duck", "Heron"],
    ["What is a group of fish called?", "School", "Pack", "Colony", "Troop"],
    ["Which animal is known for producing ink as a defense?", "Squid", "Sea horse", "Clownfish", "Crab"],
    ["Which insect begins life as a larva called a grub?", "Beetle", "Butterfly", "Mosquito", "Grasshopper"],
    ["What is the largest living animal?", "Blue whale", "Elephant", "Whale shark", "Giant squid"],
    ["Which animal has quills for defense?", "Porcupine", "Mole", "Ferret", "Otter"],
    ["What do birds use a crop for?", "Storing food before digestion", "Making eggshells", "Balancing in flight", "Cleaning feathers"],
    ["Which amphibian can regrow lost limbs especially well?", "Axolotl", "Tree frog", "Toad", "Newt"],
    ["What is the name for seasonal animal movement to find food or breeding grounds?", "Migration", "Hibernation", "Molting", "Camouflage"],
    ["Which animal is famous for sleeping upside down?", "Bat", "Sloth", "Koala", "Opossum"],
    ["What is the term for an animal that is warm-blooded?", "Endothermic", "Ectothermic", "Nocturnal", "Aquatic"],
    ["Which animal has the longest neck vertebrae but the same number of neck bones as humans?", "Giraffe", "Swan", "Ostrich", "Camel"],
    ["What do sea turtles use Earths magnetic field for?", "Navigation", "Hunting fish", "Changing shell color", "Making nests"],
    ["Which bird is often associated with delivering messages historically?", "Pigeon", "Peacock", "Flamingo", "Turkey"]
  ]),
  Sports: makeQuestions([
    ["How many bases are on a baseball field?", "4", "3", "5", "6"],
    ["Which sport uses a puck?", "Hockey", "Soccer", "Tennis", "Golf"],
    ["What color card can send a soccer player off the field?", "Red", "Blue", "Green", "Purple"],
    ["How many points is a touchdown worth in American football?", "6", "3", "2", "7"],
    ["Which sport is played at Wimbledon?", "Tennis", "Cricket", "Rugby", "Swimming"],
    ["In basketball, what is it called when a player scores from far behind the arc?", "Three-pointer", "Home run", "Ace", "Try"],
    ["Which sport uses clubs and holes?", "Golf", "Bowling", "Volleyball", "Boxing"],
    ["How many players are on a soccer team on the field?", "11", "7", "9", "12"],
    ["What surface is an Olympic swimming race held in?", "Pool", "Track", "Court", "Ring"],
    ["Which sport has a position called goalie?", "Soccer", "Tennis", "Baseball", "Gymnastics"],
    ["In tennis, what score comes after deuce when one player wins the next point?", "Advantage", "Love", "Set", "Break"],
    ["What Olympic event combines swimming, cycling, and running?", "Triathlon", "Pentathlon", "Decathlon", "Biathlon"],
    ["In bowling, what is it called when you knock down all pins with two rolls?", "Spare", "Strike", "Split", "Frame"],
    ["Which sport uses terms like scrum, try, and conversion?", "Rugby", "Volleyball", "Lacrosse", "Badminton"],
    ["In baseball, what is a run batted in often shortened to?", "RBI", "ERA", "MVP", "PK"],
    ["How many rings are on the Olympic flag?", "5", "4", "6", "7"],
    ["Which sport uses a shuttlecock?", "Badminton", "Squash", "Table tennis", "Pickleball"],
    ["In soccer, what is it called when a player scores three goals in one game?", "Hat trick", "Triple play", "Clean sheet", "Power play"],
    ["Which sport has a move called a slam dunk?", "Basketball", "Volleyball", "Football", "Baseball"],
    ["How many points is a free throw worth in basketball?", "1", "2", "3", "4"],
    ["In American football, what is the line called where each play begins?", "Line of scrimmage", "Goal line", "Baseline", "Service line"],
    ["Which sport is associated with the Tour de France?", "Cycling", "Running", "Skiing", "Rowing"],
    ["In baseball, what does ERA measure?", "Earned runs allowed by a pitcher", "Errors by a runner", "Extra runs after hits", "Average runs per inning by a team"],
    ["Which sport uses a pommel horse?", "Gymnastics", "Equestrian", "Wrestling", "Fencing"],
    ["In volleyball, how many hits does a team usually get before sending the ball over?", "3", "2", "4", "5"],
    ["Which sport uses an epee?", "Fencing", "Archery", "Curling", "Polo"],
    ["What is the target called in archery?", "Bullseye", "Net", "Cup", "Plate"],
    ["In golf, what is one stroke under par called?", "Birdie", "Eagle", "Bogey", "Ace"],
    ["Which winter sport uses stones and brooms?", "Curling", "Luge", "Biathlon", "Skeleton"],
    ["In track, what race is exactly one lap on a standard outdoor track?", "400 meters", "100 meters", "800 meters", "1500 meters"],
    ["Which sport is played on a diamond?", "Baseball", "Cricket", "Lacrosse", "Rugby"],
    ["In hockey, what is a power play?", "One team has more skaters due to a penalty", "The game goes to overtime", "A goalie scores", "A player takes a penalty shot"],
    ["Which sport has a Grand Slam tournament called the US Open?", "Tennis", "Golf", "Bowling", "Swimming"],
    ["What is the maximum break in snooker?", "147", "100", "180", "300"],
    ["Which sport uses the terms love and deuce?", "Tennis", "Cricket", "Curling", "Boxing"],
    ["In boxing, what does KO stand for?", "Knockout", "Keep out", "Key offense", "Knee opening"],
    ["Which sport includes the positions pitcher and catcher?", "Baseball", "Cricket", "Softball only", "Lacrosse"],
    ["In soccer, what is a clean sheet?", "A game with no goals allowed by a team", "A game with no yellow cards", "A brand-new field", "A tie after overtime"],
    ["Which sport uses the term alley-oop?", "Basketball", "Tennis", "Hockey", "Golf"],
    ["How many players are on the court for one NBA team during play?", "5", "4", "6", "7"],
    ["Which sport is famous for the Stanley Cup?", "Ice hockey", "Basketball", "Baseball", "Soccer"],
    ["In cricket, what is a wicket?", "A set of stumps and bails", "The ball boundary", "A player helmet", "A scoring zone"],
    ["Which sport is played at the Super Bowl?", "American football", "Baseball", "Basketball", "Soccer"],
    ["What is the name of the area where a golfer begins a hole?", "Tee box", "Green", "Bunker", "Fairway"],
    ["In swimming, which stroke is usually the fastest?", "Freestyle", "Breaststroke", "Backstroke", "Butterfly"],
    ["Which sport has a libero position?", "Volleyball", "Basketball", "Soccer", "Water polo"],
    ["What is a marathon distance closest to?", "26.2 miles", "13.1 miles", "10 miles", "50 miles"],
    ["Which sport uses a yellow jersey for the overall leader in a famous race?", "Cycling", "Sailing", "Running", "Skiing"],
    ["In baseball, what is a grand slam?", "A home run with the bases loaded", "Four strikeouts in a row", "A perfect inning", "A game-winning catch"],
    ["Which sport has the Ryder Cup?", "Golf", "Tennis", "Cricket", "Rugby"],
    ["In football, what does a quarterback usually do?", "Throws or hands off the ball", "Kicks every field goal", "Guards the net", "Calls balls and strikes"],
    ["Which sport uses a foil?", "Fencing", "Fishing", "Sailing", "Gymnastics"],
    ["In basketball, what is traveling?", "Moving illegally with the ball without dribbling", "Blocking a shot", "Shooting from half court", "Calling timeout"],
    ["Which sport uses a crease near the goal?", "Hockey", "Baseball", "Golf", "Tennis"],
    ["What is the Paralympics?", "An international sports event for athletes with disabilities", "A winter-only youth tournament", "A college championship", "A single marathon race"],
    ["In soccer, where is a penalty kick taken from?", "Penalty spot", "Corner arc", "Halfway line", "Goal area"],
    ["Which sport is associated with a velodrome?", "Track cycling", "Horse racing", "Speed skating", "Rowing"],
    ["In tennis, what is an ace?", "A serve the receiver cannot touch", "A shot that hits the net", "A winning volley only", "A point after deuce"],
    ["Which sport has a coxswain?", "Rowing", "Sailing", "Cycling", "Ski jumping"],
    ["In baseball, how many outs end a half-inning?", "3", "2", "4", "5"]
  ]),
  Music: makeQuestions([
    ["Which instrument has black and white keys?", "Piano", "Drum", "Trumpet", "Violin"],
    ["What do you call a group of singers?", "Choir", "Team", "Fleet", "Pack"],
    ["How many strings does a standard guitar usually have?", "6", "4", "8", "10"],
    ["Which instrument is played with sticks?", "Drums", "Flute", "Harp", "Tuba"],
    ["What is a person who writes music called?", "Composer", "Painter", "Referee", "Pilot"],
    ["Which word means how fast music is played?", "Tempo", "Flavor", "Texture", "Volume"],
    ["Which instrument is usually bowed?", "Violin", "Clarinet", "Trombone", "Ukulele"],
    ["What symbol is often used to write music notes?", "Staff", "Map", "Grid", "Clock"],
    ["Which voice is usually higher?", "Soprano", "Bass", "Baritone", "Tenor"],
    ["What do musicians follow to stay together in time?", "Beat", "Recipe", "Scoreboard", "Compass"],
    ["Which musical marking means to gradually get louder?", "Crescendo", "Staccato", "Fermata", "Adagio"],
    ["How many beats does a quarter note usually get in 4/4 time?", "1", "2", "3", "4"],
    ["Which instrument family does the oboe belong to?", "Woodwinds", "Brass", "Strings", "Percussion"],
    ["What is the distance between two notes with the same letter name called?", "Octave", "Chord", "Scale", "Measure"],
    ["Which clef is commonly used for lower-pitched instruments like cello and bassoon?", "Bass clef", "Treble clef", "Alto clef", "Percussion clef"],
    ["What does forte mean in music?", "Loud", "Soft", "Fast", "Slow"],
    ["What does piano mean as a dynamic marking?", "Soft", "Loud", "Quick", "Detached"],
    ["Which instrument has pedals and many strings inside a large frame?", "Harp", "Accordion", "Banjo", "Saxophone"],
    ["What is a chord?", "Three or more notes played together", "A single drum hit", "A written lyric", "A repeated rhythm only"],
    ["Which period came after the Baroque era in Western classical music?", "Classical", "Medieval", "Romantic", "Modern"],
    ["Who composed The Four Seasons?", "Antonio Vivaldi", "Ludwig van Beethoven", "Johann Strauss", "Claude Debussy"],
    ["Which composer became famous while losing his hearing?", "Ludwig van Beethoven", "Wolfgang Mozart", "Joseph Haydn", "Frederic Chopin"],
    ["What is syncopation?", "Emphasis on unexpected beats", "Playing only soft notes", "Singing without words", "Repeating one pitch"],
    ["Which instrument family includes the trombone?", "Brass", "Woodwinds", "Strings", "Percussion"],
    ["What is a metronome used for?", "Keeping a steady tempo", "Tuning guitar strings", "Recording vocals", "Changing key signatures"],
    ["What is the name for music sung without instruments?", "A cappella", "Concerto", "Overture", "Sonata"],
    ["Which symbol raises a note by a half step?", "Sharp", "Flat", "Rest", "Tie"],
    ["Which symbol lowers a note by a half step?", "Flat", "Sharp", "Accent", "Repeat sign"],
    ["What is a rest in written music?", "A silent beat or pause", "A louder note", "A repeated chorus", "A final chord"],
    ["Which instrument is a single-reed woodwind?", "Clarinet", "Flute", "Oboe", "Bassoon"],
    ["Which instrument is a double-reed woodwind?", "Oboe", "Clarinet", "Saxophone", "Recorder"],
    ["What is improvisation?", "Making music in the moment", "Playing from memory only", "Tuning before a concert", "Writing lyrics on paper"],
    ["Which music genre is strongly associated with improvisation and swing?", "Jazz", "Opera", "Marching band", "Gregorian chant"],
    ["What is a refrain often called in popular music?", "Chorus", "Verse", "Bridge", "Intro"],
    ["Which part of a song usually tells different lyrics each time?", "Verse", "Chorus", "Hook", "Outro"],
    ["What is the bridge in a song?", "A contrasting section", "The first drumbeat", "The final note", "A repeated title only"],
    ["What does BPM stand for?", "Beats per minute", "Bass pitch mode", "Band practice manual", "Bar phrase measure"],
    ["What is a key signature?", "Sharps or flats that show the key", "The title of a song", "A singers autograph", "The loudest section"],
    ["Which scale pattern sounds bright and happy to many listeners?", "Major", "Minor", "Chromatic", "Whole-tone only"],
    ["Which scale pattern often sounds darker or sadder to many listeners?", "Minor", "Major", "Pentatonic only", "Blues only"],
    ["What is vibrato?", "A slight wavering of pitch", "A sudden silence", "A very fast tempo", "A written repeat"],
    ["What is staccato?", "Short and detached", "Smooth and connected", "Very loud", "Very slow"],
    ["What is legato?", "Smooth and connected", "Short and detached", "Suddenly louder", "Without rhythm"],
    ["Which instrument is part of a standard string quartet besides violin, viola, and cello?", "Second violin", "Double bass", "Harp", "Guitar"],
    ["How many lines are on a standard musical staff?", "5", "4", "6", "7"],
    ["What is a measure in music?", "A group of beats", "A tuning peg", "A type of microphone", "A singers range"],
    ["What is timbre?", "The unique tone color of a sound", "The speed of a song", "The number of beats", "The written lyrics"],
    ["Which voice type is usually the lowest male voice?", "Bass", "Tenor", "Alto", "Soprano"],
    ["Which voice type is usually between soprano and tenor in choirs?", "Alto", "Bass", "Baritone", "Treble"],
    ["What does ritardando mean?", "Gradually slowing down", "Gradually getting louder", "Playing detached", "Changing instruments"],
    ["Which instrument is commonly associated with the blues and is held to the mouth?", "Harmonica", "Cello", "Timpani", "Mandolin"],
    ["What is an overture?", "An instrumental opening to a larger work", "A drum solo", "A singers warmup", "A final applause"],
    ["Which percussion instrument is tuned and has large copper bowls?", "Timpani", "Snare drum", "Tambourine", "Cymbals"],
    ["What is a duet?", "Music for two performers", "Music for three performers", "A full choir", "A solo piece"],
    ["What is a trio?", "Music for three performers", "Music for two performers", "A marching band", "A full orchestra"],
    ["Which instrument uses a slide to change pitch?", "Trombone", "Trumpet", "Clarinet", "Viola"],
    ["What is a conductor mainly responsible for?", "Leading performers and keeping time", "Selling tickets", "Writing every lyric", "Building instruments"],
    ["Which instrument is often called the king of instruments?", "Pipe organ", "Piano", "Tuba", "Violin"],
    ["What is a lullaby?", "A soothing song often for sleep", "A fast dance tune", "A national song", "A fan chant"],
    ["Which music notation mark tells musicians to repeat a section?", "Repeat sign", "Treble clef", "Time signature", "Accent mark"]
  ]),
  Food: makeQuestions([
    ["Which fruit is yellow and curved?", "Banana", "Apple", "Grape", "Blueberry"],
    ["What is the main ingredient in guacamole?", "Avocado", "Potato", "Carrot", "Corn"],
    ["Which food is often sliced into triangles?", "Pizza", "Soup", "Rice", "Yogurt"],
    ["What do bees make?", "Honey", "Butter", "Pasta", "Jam"],
    ["Which vegetable is orange?", "Carrot", "Lettuce", "Eggplant", "Pea"],
    ["What grain is sushi often made with?", "Rice", "Oats", "Barley", "Corn"],
    ["Which treat is made from cacao?", "Chocolate", "Pretzel", "Popcorn", "Pancake"],
    ["Which fruit has seeds on the outside?", "Strawberry", "Orange", "Pear", "Peach"],
    ["Which dairy food is often melted on pizza?", "Cheese", "Ice cream", "Milk", "Yogurt"],
    ["What is bread baked from?", "Dough", "Syrup", "Juice", "Sauce"],
    ["Which grain is traditionally used to make risotto?", "Arborio rice", "Quinoa", "Bulgur wheat", "Millet"],
    ["What process makes bread dough rise?", "Fermentation", "Freezing", "Caramelizing", "Pickling"],
    ["Which spice gives many curries and mustards a bright yellow color?", "Turmeric", "Cinnamon", "Nutmeg", "Paprika"],
    ["What is tofu most commonly made from?", "Soybeans", "Chickpeas", "Almonds", "Rice"],
    ["Which cooking method uses hot air circulating around food?", "Roasting", "Boiling", "Poaching", "Steaming"],
    ["What is pasta traditionally made from?", "Durum wheat semolina", "Cornmeal", "Rice flour only", "Potato starch"],
    ["Which fruit is used to make traditional raisins?", "Grapes", "Plums", "Dates", "Figs"],
    ["What is the main ingredient in hummus?", "Chickpeas", "Lentils", "Peanuts", "Cauliflower"],
    ["Which nut is used to make marzipan?", "Almond", "Walnut", "Pistachio", "Cashew"],
    ["What cooking method cooks food gently in liquid below boiling?", "Poaching", "Frying", "Grilling", "Roasting"],
    ["What is kimchi usually made from?", "Fermented cabbage", "Boiled potatoes", "Pickled peaches", "Roasted corn"],
    ["Which cuisine is sushi most associated with?", "Japanese", "Italian", "Mexican", "Greek"],
    ["Which country is famous for tacos as a traditional food?", "Mexico", "India", "France", "Thailand"],
    ["What is mozzarella traditionally made from?", "Milk", "Eggs", "Soybeans", "Wheat"],
    ["What gives sourdough bread its tangy flavor?", "Wild yeast and bacteria", "Extra sugar", "Baking powder only", "Cocoa"],
    ["Which food is made by curdling soy milk?", "Tofu", "Paneer", "Yogurt", "Polenta"],
    ["What is the main ingredient in traditional pesto?", "Basil", "Cilantro", "Spinach", "Mint"],
    ["Which grain is ground to make polenta?", "Corn", "Rice", "Wheat", "Rye"],
    ["Which spice comes from dried flower buds?", "Cloves", "Cumin", "Saffron", "Pepper"],
    ["What is saffron harvested from?", "Crocus flower stigmas", "Vanilla pods", "Rose petals", "Mustard seeds"],
    ["Which fruit is dried to make prunes?", "Plums", "Apricots", "Figs", "Dates"],
    ["Which legume is used to make falafel?", "Chickpeas", "Black beans", "Green peas", "Soybeans"],
    ["What is the main ingredient in traditional sauerkraut?", "Cabbage", "Cucumber", "Turnip", "Celery"],
    ["Which sauce is made from egg yolk and oil emulsified together?", "Mayonnaise", "Ketchup", "Soy sauce", "Barbecue sauce"],
    ["Which ingredient makes meringue light and foamy?", "Egg whites", "Butter", "Flour", "Cream cheese"],
    ["What does al dente mean for pasta?", "Firm to the bite", "Very soft", "Served cold", "Stuffed with cheese"],
    ["Which food is measured on the Scoville scale?", "Chili peppers", "Cheese", "Bread", "Chocolate"],
    ["Which vitamin is citrus fruit especially known for?", "Vitamin C", "Vitamin D", "Vitamin B12", "Vitamin K"],
    ["What is the main ingredient in traditional miso?", "Fermented soybeans", "Roasted peanuts", "Coconut milk", "Ground rice"],
    ["Which drink is made by fermenting tea with a culture?", "Kombucha", "Lemonade", "Smoothie", "Hot chocolate"],
    ["What is the main ingredient in baba ganoush?", "Eggplant", "Avocado", "Pumpkin", "Carrot"],
    ["Which cheese is commonly used in Greek salad?", "Feta", "Cheddar", "Brie", "Gouda"],
    ["Which herb is common in tabbouleh?", "Parsley", "Rosemary", "Sage", "Dill"],
    ["What is a tortilla traditionally made from in many Mexican dishes?", "Corn or wheat", "Rice or oats", "Potato or beans", "Barley or rye"],
    ["What is the process of browning sugar called?", "Caramelization", "Fermentation", "Pasteurization", "Emulsification"],
    ["Which cooking method uses direct radiant heat from below?", "Grilling", "Steaming", "Braising", "Poaching"],
    ["What is braising?", "Cooking slowly with a small amount of liquid", "Cooking only in dry air", "Freezing quickly", "Whipping with air"],
    ["Which ingredient is used to make traditional tempura batter light?", "Cold water", "Hot milk", "Tomato juice", "Melted cheese"],
    ["Which food is famous for being made in layers with pasta, sauce, and cheese?", "Lasagna", "Risotto", "Curry", "Gumbo"],
    ["Which seed is used to make tahini?", "Sesame", "Sunflower", "Pumpkin", "Poppy"],
    ["What is the main ingredient in traditional gazpacho?", "Tomatoes", "Potatoes", "Apples", "Mushrooms"],
    ["Which fruit is used to make traditional guava paste?", "Guava", "Mango", "Papaya", "Lychee"],
    ["What is yeast mainly used for in baking?", "Helping dough rise", "Making food colder", "Adding crunch only", "Changing color to blue"],
    ["Which sauce is traditionally served with eggs Benedict?", "Hollandaise", "Marinara", "Teriyaki", "Pesto"],
    ["Which grain is used to make oatmeal?", "Oats", "Wheat", "Corn", "Buckwheat"],
    ["What is the main ingredient in gnocchi most commonly?", "Potato", "Rice", "Corn", "Beans"],
    ["Which fruit is known as a stone fruit?", "Peach", "Banana", "Grape", "Orange"],
    ["Which dairy product is made by fermenting milk with bacteria?", "Yogurt", "Butter", "Cream", "Ice"],
    ["What is the main flavoring in vanilla extract?", "Vanilla beans", "Cocoa beans", "Coffee beans", "Tonka leaves"],
    ["Which food is made from pressed curds of milk?", "Cheese", "Jam", "Bread", "Noodles"]
  ]),
  Movies: makeQuestions([
    ["What do actors say when they read their parts?", "Lines", "Scores", "Recipes", "Rules"],
    ["What is a movie preview called?", "Trailer", "Poster", "Ticket", "Scene"],
    ["Who directs a movie?", "Director", "Goalie", "Chef", "Dentist"],
    ["What is animation made from?", "Drawings or computer images", "Only live news", "Cookbooks", "Scoreboards"],
    ["Where do many people go to watch a new movie?", "Theater", "Library desk", "Airport gate", "Gym court"],
    ["What is a movies music often called?", "Soundtrack", "Headline", "Blueprint", "Menu"],
    ["Which job designs costumes for characters?", "Costume designer", "Referee", "Pilot", "Baker"],
    ["What device records scenes for a movie?", "Camera", "Microwave", "Compass", "Toaster"],
    ["What do you call the written story for a movie?", "Script", "Map", "Receipt", "Calendar"],
    ["What happens at the end of many movies listing the people who worked on it?", "Credits", "Practice", "Warm-up", "Recipe"],
    ["What does a cinematographer mainly help create?", "The look of the camera shots", "The snack menu", "The ticket price", "The theater seats"],
    ["What is a storyboard used for before filming?", "Planning shots with drawings", "Selling popcorn", "Printing tickets", "Choosing seat numbers"],
    ["Which movie job is responsible for arranging recorded sounds after filming?", "Sound editor", "Costume designer", "Stunt double", "Casting director"],
    ["What does CGI stand for in movies?", "Computer-generated imagery", "Camera grip instructions", "Color grading index", "Cinema guest invitation"],
    ["What is the name for a scene filmed but not included in the final movie?", "Deleted scene", "Opening credit", "Wide release", "Box office"],
    ["What is a close-up shot?", "A shot framing a subject tightly", "A shot from very far away", "A shot without sound", "A shot after credits"],
    ["What is a wide shot usually used to show?", "A broad view of the setting", "Only a characters eyes", "The script pages", "The theater lobby"],
    ["What is voice-over?", "Narration heard over the image", "A silent title card", "A camera lens type", "A costume fitting"],
    ["What is a sequel?", "A movie that continues an earlier story", "A movie made before the original", "A movie with no actors", "A short preview"],
    ["What is a prequel?", "A story set before an earlier movie", "A movie shown after credits", "A theater snack", "A sound effect"],
    ["What is stop-motion animation?", "Animation made by photographing small movements", "Animation only made underwater", "Filming with no camera", "Drawing directly on film tickets"],
    ["What is a film score?", "Original music composed for a movie", "The number of tickets sold", "A list of actors", "A critic rating only"],
    ["Who is in charge of editing shots together?", "Film editor", "Production designer", "Boom operator", "Casting director"],
    ["What does a boom operator usually hold?", "A microphone on a pole", "A camera lens", "A costume rack", "A clapperboard only"],
    ["What is a clapperboard used for?", "Syncing picture and sound", "Selling tickets", "Painting sets", "Making popcorn"],
    ["What is a cameo?", "A brief appearance by a known person", "A movie poster", "A deleted scene", "A camera movement"],
    ["What is a genre?", "A type or category of movie", "A movie ticket price", "A lighting tool", "A film reel size"],
    ["Which genre often includes clues and solving a puzzle?", "Mystery", "Musical", "Documentary", "Slapstick"],
    ["Which genre often features songs as part of the story?", "Musical", "Western", "Mystery", "Documentary"],
    ["What is a documentary?", "A nonfiction movie about real people or events", "A movie with only cartoons", "A movie with no camera", "A theater rule list"],
    ["What is green screen used for?", "Adding backgrounds or effects later", "Changing ticket colors", "Recording only music", "Printing subtitles"],
    ["What is ADR in filmmaking?", "Re-recording dialogue after filming", "Designing costumes", "Choosing camera angles", "Selling merchandise"],
    ["What is a prop?", "An object used by actors in a scene", "A movie theater seat", "A camera battery", "A music note"],
    ["Who chooses actors for roles?", "Casting director", "Sound mixer", "Editor", "Set decorator"],
    ["What is production design?", "Creating the visual world of the movie", "Writing ticket prices", "Reviewing snacks", "Scheduling trailers"],
    ["What is a stunt double?", "A performer who does risky action for an actor", "A second director", "A backup camera", "A duplicate ticket"],
    ["What is the box office?", "Movie ticket sales", "The camera room", "The costume closet", "A sound booth"],
    ["What is a scene?", "A section of a movie in one time or place", "A whole movie series", "A theater hallway", "A camera tripod"],
    ["What is a montage?", "A sequence of short shots showing time or progress", "A single uncut shot only", "A theater announcement", "A costume tag"],
    ["What is an establishing shot?", "A shot that shows where the scene is set", "A shot of only shoes", "A shot with no actors", "A shot after the credits"],
    ["What is a protagonist?", "The main character", "The background music", "The movie theater", "The final scene"],
    ["What is an antagonist?", "A character or force opposing the main character", "A camera assistant", "A movie snack", "A costume color"],
    ["What does PG stand for in movie ratings?", "Parental guidance", "Picture grade", "Preview general", "Public gallery"],
    ["What is a rating meant to help audiences decide?", "Age appropriateness", "Ticket price", "Camera quality", "The number of actors"],
    ["What is a screenplay?", "The written script for a movie", "A theater curtain", "A camera filter", "A movie snack list"],
    ["What is a plot twist?", "An unexpected change in the story", "A dance move", "A camera battery change", "A poster design"],
    ["What is a franchise in movies?", "A connected series of films and media", "A single movie ticket", "A camera tripod", "A theater uniform"],
    ["What is a reboot?", "A new version of an existing story or series", "A movie with no ending", "A kind of popcorn", "A deleted song"],
    ["What is a remake?", "A new version of an earlier movie", "A film shown backward", "A preview before a movie", "A theater renovation only"],
    ["What is a subtitle?", "Text showing dialogue or translation", "A hidden camera", "A second title poster", "A costume accessory"],
    ["What is dubbing?", "Replacing spoken dialogue with another recording", "Painting a set", "Changing seats", "Adding popcorn butter"],
    ["What is a frame in film?", "One still image in a moving picture", "A theater doorway", "A poster border only", "A camera case"],
    ["What does FPS mean for video?", "Frames per second", "Film poster size", "Final preview score", "Fast picture sound"],
    ["What is a dolly shot?", "A camera movement on a wheeled platform", "A puppet scene", "A costume test", "A musical number"],
    ["What is a pan shot?", "Turning the camera left or right", "Moving the camera underwater", "Filming without sound", "Showing credits early"],
    ["What is a tilt shot?", "Moving the camera up or down", "Changing the actors voice", "Editing the script", "Warming the lights"],
    ["What is lighting used for in movies?", "Setting mood and making subjects visible", "Selling snacks", "Writing dialogue", "Printing tickets"],
    ["What is post-production?", "Work after filming like editing and sound", "The first day of filming", "Buying tickets", "Building the theater"],
    ["What is a premiere?", "The first public showing of a movie", "The last deleted scene", "A camera lens", "A costume rack"],
    ["What is a film festival?", "An event where movies are shown and celebrated", "A sports tournament", "A music-only concert", "A food market"]
  ])
};
