import type { Category, Question } from "../shared/types";

export const fallbackQuestions: Record<Category, Question[]> = {
  Animals: [
    { question: "What is the largest land animal?", choices: ["Elephant", "Rhino", "Hippo", "Giraffe"], correctAnswer: "Elephant" },
    { question: "Which animal is known for changing color?", choices: ["Chameleon", "Panda", "Penguin", "Koala"], correctAnswer: "Chameleon" },
    { question: "What do caterpillars become?", choices: ["Butterflies", "Frogs", "Crabs", "Sparrows"], correctAnswer: "Butterflies" },
    { question: "Which bird cannot fly?", choices: ["Ostrich", "Eagle", "Robin", "Parrot"], correctAnswer: "Ostrich" },
    { question: "What animal is famous for building dams?", choices: ["Beaver", "Fox", "Seal", "Moose"], correctAnswer: "Beaver" },
    { question: "How many legs does a spider have?", choices: ["8", "6", "10", "12"], correctAnswer: "8" },
    { question: "What is a baby goat called?", choices: ["Kid", "Cub", "Calf", "Joey"], correctAnswer: "Kid" },
    { question: "Which animal is the tallest?", choices: ["Giraffe", "Camel", "Horse", "Bison"], correctAnswer: "Giraffe" },
    { question: "What do pandas mostly eat?", choices: ["Bamboo", "Fish", "Apples", "Grass"], correctAnswer: "Bamboo" },
    { question: "Which sea animal has eight arms?", choices: ["Octopus", "Dolphin", "Sea turtle", "Clam"], correctAnswer: "Octopus" },
    { question: "Which mammal can truly fly instead of only glide?", choices: ["Bat", "Flying squirrel", "Sugar glider", "Colugo"], correctAnswer: "Bat" },
    { question: "What is the name for animals that are active mostly at night?", choices: ["Nocturnal", "Migratory", "Venomous", "Amphibious"], correctAnswer: "Nocturnal" },
    { question: "Which animal group does a salamander belong to?", choices: ["Amphibians", "Reptiles", "Fish", "Mammals"], correctAnswer: "Amphibians" },
    { question: "What do baleen whales use baleen plates for?", choices: ["Filtering food from water", "Making loud clicks", "Digging in sand", "Steering while swimming"], correctAnswer: "Filtering food from water" },
    { question: "Which big cat is best known for its black tear-like facial marks?", choices: ["Cheetah", "Lion", "Jaguar", "Leopard"], correctAnswer: "Cheetah" }
  ],
  Sports: [
    { question: "How many bases are on a baseball field?", choices: ["4", "3", "5", "6"], correctAnswer: "4" },
    { question: "Which sport uses a puck?", choices: ["Hockey", "Soccer", "Tennis", "Golf"], correctAnswer: "Hockey" },
    { question: "What color card can send a soccer player off the field?", choices: ["Red", "Blue", "Green", "Purple"], correctAnswer: "Red" },
    { question: "How many points is a touchdown worth in American football?", choices: ["6", "3", "2", "7"], correctAnswer: "6" },
    { question: "Which sport is played at Wimbledon?", choices: ["Tennis", "Cricket", "Rugby", "Swimming"], correctAnswer: "Tennis" },
    { question: "In basketball, what is it called when a player scores from far behind the arc?", choices: ["Three-pointer", "Home run", "Ace", "Try"], correctAnswer: "Three-pointer" },
    { question: "Which sport uses clubs and holes?", choices: ["Golf", "Bowling", "Volleyball", "Boxing"], correctAnswer: "Golf" },
    { question: "How many players are on a soccer team on the field?", choices: ["11", "7", "9", "12"], correctAnswer: "11" },
    { question: "What surface is an Olympic swimming race held in?", choices: ["Pool", "Track", "Court", "Ring"], correctAnswer: "Pool" },
    { question: "Which sport has a position called goalie?", choices: ["Soccer", "Tennis", "Baseball", "Gymnastics"], correctAnswer: "Soccer" },
    { question: "In tennis, what score comes after deuce when one player wins the next point?", choices: ["Advantage", "Love", "Set", "Break"], correctAnswer: "Advantage" },
    { question: "What Olympic event combines swimming, cycling, and running?", choices: ["Triathlon", "Pentathlon", "Decathlon", "Biathlon"], correctAnswer: "Triathlon" },
    { question: "In bowling, what is it called when you knock down all pins with two rolls?", choices: ["Spare", "Strike", "Split", "Frame"], correctAnswer: "Spare" },
    { question: "Which sport uses terms like scrum, try, and conversion?", choices: ["Rugby", "Volleyball", "Lacrosse", "Badminton"], correctAnswer: "Rugby" },
    { question: "In baseball, what is a run batted in often shortened to?", choices: ["RBI", "ERA", "MVP", "PK"], correctAnswer: "RBI" }
  ],
  Music: [
    { question: "Which instrument has black and white keys?", choices: ["Piano", "Drum", "Trumpet", "Violin"], correctAnswer: "Piano" },
    { question: "What do you call a group of singers?", choices: ["Choir", "Team", "Fleet", "Pack"], correctAnswer: "Choir" },
    { question: "How many strings does a standard guitar usually have?", choices: ["6", "4", "8", "10"], correctAnswer: "6" },
    { question: "Which instrument is played with sticks?", choices: ["Drums", "Flute", "Harp", "Tuba"], correctAnswer: "Drums" },
    { question: "What is a person who writes music called?", choices: ["Composer", "Painter", "Referee", "Pilot"], correctAnswer: "Composer" },
    { question: "Which word means how fast music is played?", choices: ["Tempo", "Flavor", "Texture", "Volume"], correctAnswer: "Tempo" },
    { question: "Which instrument is usually bowed?", choices: ["Violin", "Clarinet", "Trombone", "Ukulele"], correctAnswer: "Violin" },
    { question: "What symbol is often used to write music notes?", choices: ["Staff", "Map", "Grid", "Clock"], correctAnswer: "Staff" },
    { question: "Which voice is usually higher?", choices: ["Soprano", "Bass", "Baritone", "Tenor"], correctAnswer: "Soprano" },
    { question: "What do musicians follow to stay together in time?", choices: ["Beat", "Recipe", "Scoreboard", "Compass"], correctAnswer: "Beat" },
    { question: "Which musical marking means to gradually get louder?", choices: ["Crescendo", "Staccato", "Fermata", "Adagio"], correctAnswer: "Crescendo" },
    { question: "How many beats does a quarter note usually get in 4/4 time?", choices: ["1", "2", "3", "4"], correctAnswer: "1" },
    { question: "Which instrument family does the oboe belong to?", choices: ["Woodwinds", "Brass", "Strings", "Percussion"], correctAnswer: "Woodwinds" },
    { question: "What is the distance between two notes with the same letter name called?", choices: ["Octave", "Chord", "Scale", "Measure"], correctAnswer: "Octave" },
    { question: "Which clef is commonly used for lower-pitched instruments like cello and bassoon?", choices: ["Bass clef", "Treble clef", "Alto clef", "Percussion clef"], correctAnswer: "Bass clef" }
  ],
  Food: [
    { question: "Which fruit is yellow and curved?", choices: ["Banana", "Apple", "Grape", "Blueberry"], correctAnswer: "Banana" },
    { question: "What is the main ingredient in guacamole?", choices: ["Avocado", "Potato", "Carrot", "Corn"], correctAnswer: "Avocado" },
    { question: "Which food is often sliced into triangles?", choices: ["Pizza", "Soup", "Rice", "Yogurt"], correctAnswer: "Pizza" },
    { question: "What do bees make?", choices: ["Honey", "Butter", "Pasta", "Jam"], correctAnswer: "Honey" },
    { question: "Which vegetable is orange?", choices: ["Carrot", "Lettuce", "Eggplant", "Pea"], correctAnswer: "Carrot" },
    { question: "What grain is sushi often made with?", choices: ["Rice", "Oats", "Barley", "Corn"], correctAnswer: "Rice" },
    { question: "Which treat is made from cacao?", choices: ["Chocolate", "Pretzel", "Popcorn", "Pancake"], correctAnswer: "Chocolate" },
    { question: "Which fruit has seeds on the outside?", choices: ["Strawberry", "Orange", "Pear", "Peach"], correctAnswer: "Strawberry" },
    { question: "Which dairy food is often melted on pizza?", choices: ["Cheese", "Ice cream", "Milk", "Yogurt"], correctAnswer: "Cheese" },
    { question: "What is bread baked from?", choices: ["Dough", "Syrup", "Juice", "Sauce"], correctAnswer: "Dough" },
    { question: "Which grain is traditionally used to make risotto?", choices: ["Arborio rice", "Quinoa", "Bulgur wheat", "Millet"], correctAnswer: "Arborio rice" },
    { question: "What process makes bread dough rise?", choices: ["Fermentation", "Freezing", "Caramelizing", "Pickling"], correctAnswer: "Fermentation" },
    { question: "Which spice gives many curries and mustards a bright yellow color?", choices: ["Turmeric", "Cinnamon", "Nutmeg", "Paprika"], correctAnswer: "Turmeric" },
    { question: "What is tofu most commonly made from?", choices: ["Soybeans", "Chickpeas", "Almonds", "Rice"], correctAnswer: "Soybeans" },
    { question: "Which cooking method uses hot air circulating around food?", choices: ["Roasting", "Boiling", "Poaching", "Steaming"], correctAnswer: "Roasting" }
  ],
  Movies: [
    { question: "What do actors say when they read their parts?", choices: ["Lines", "Scores", "Recipes", "Rules"], correctAnswer: "Lines" },
    { question: "What is a movie preview called?", choices: ["Trailer", "Poster", "Ticket", "Scene"], correctAnswer: "Trailer" },
    { question: "Who directs a movie?", choices: ["Director", "Goalie", "Chef", "Dentist"], correctAnswer: "Director" },
    { question: "What is animation made from?", choices: ["Drawings or computer images", "Only live news", "Cookbooks", "Scoreboards"], correctAnswer: "Drawings or computer images" },
    { question: "Where do many people go to watch a new movie?", choices: ["Theater", "Library desk", "Airport gate", "Gym court"], correctAnswer: "Theater" },
    { question: "What is a movie's music often called?", choices: ["Soundtrack", "Headline", "Blueprint", "Menu"], correctAnswer: "Soundtrack" },
    { question: "Which job designs costumes for characters?", choices: ["Costume designer", "Referee", "Pilot", "Baker"], correctAnswer: "Costume designer" },
    { question: "What device records scenes for a movie?", choices: ["Camera", "Microwave", "Compass", "Toaster"], correctAnswer: "Camera" },
    { question: "What do you call the written story for a movie?", choices: ["Script", "Map", "Receipt", "Calendar"], correctAnswer: "Script" },
    { question: "What happens at the end of many movies listing the people who worked on it?", choices: ["Credits", "Practice", "Warm-up", "Recipe"], correctAnswer: "Credits" },
    { question: "What does a cinematographer mainly help create?", choices: ["The look of the camera shots", "The snack menu", "The ticket price", "The theater seats"], correctAnswer: "The look of the camera shots" },
    { question: "What is a storyboard used for before filming?", choices: ["Planning shots with drawings", "Selling popcorn", "Printing tickets", "Choosing seat numbers"], correctAnswer: "Planning shots with drawings" },
    { question: "Which movie job is responsible for arranging recorded sounds after filming?", choices: ["Sound editor", "Costume designer", "Stunt double", "Casting director"], correctAnswer: "Sound editor" },
    { question: "What does CGI stand for in movies?", choices: ["Computer-generated imagery", "Camera grip instructions", "Color grading index", "Cinema guest invitation"], correctAnswer: "Computer-generated imagery" },
    { question: "What is the name for a scene filmed but not included in the final movie?", choices: ["Deleted scene", "Opening credit", "Wide release", "Box office"], correctAnswer: "Deleted scene" }
  ]
};
